services:
  app:
    image: elasticproject
    container_name: elasticproject
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080"
    depends_on:
      - db_pg
      - elasticksearch
    environment:
       SPRING_DATASOURCE_URL: 'dbc:postgresql://db_pg:5432/elasticsearch'

  db_pg:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: elasticsearch
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 13092001
    ports:
      - "5432"
  elasticksearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.25
    container_name: elasticksearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"